version: '3'

services:
  control_node:
    build:
      context: .
      dockerfile: ControlNode.Dockerfile
    volumes:
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - worker_node_1
      - worker_node_2

  worker_node_1:
    container_name: worker_node_1
    build:
      context: .
      dockerfile: WorkerNode.Dockerfile
    image: worker_node
    hostname: worker1
    ports:
      - "8081:80"

  worker_node_2:
    container_name: worker_node_2
    build:
      context: .
      dockerfile: WorkerNode.Dockerfile
    image: worker_node
    hostname: worker2
    ports:
      - "8082:80"
